"""alter estado table

Revision ID: 7a998db8f8e6
Revises: f422f2b74d1e
Create Date: 2026-02-13 14:37:27.963097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a998db8f8e6'
down_revision = 'f422f2b74d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarifa_base_kwh', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estados', schema=None) as batch_op:
        batch_op.drop_column('tarifa_base_kwh')

    # ### end Alembic commands ###
