"""add solucao_fornecedor table

Revision ID: 8e864cd6e44e
Revises: d7e8ad3966a4
Create Date: 2026-02-14 15:16:00.518672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e864cd6e44e'
down_revision = 'd7e8ad3966a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solucao_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solucao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('custo_kwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solucao_id'], ['solucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solucao_id', 'fornecedor_id', 'estado_id', name='uq_solucao_fornecedor_estado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solucao_fornecedor')
    # ### end Alembic commands ###
