"""initial structure

Revision ID: d7e8ad3966a4
Revises: 
Create Date: 2026-02-14 14:59:43.162526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8ad3966a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('tarifa_base_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('estado_origem_id', sa.Integer(), nullable=False),
    sa.Column('total_clientes', sa.Integer(), nullable=False),
    sa.Column('avaliacoes_media', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estado_origem_id'], ['estados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedores')
    op.drop_table('solucoes')
    op.drop_table('estados')
    # ### end Alembic commands ###
