"""add fields to fornecedores

Revision ID: e7647669aca2
Revises: c6f4ec262fce
Create Date: 2026-02-14 13:32:29.884174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7647669aca2'
down_revision = 'c6f4ec262fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_origem_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_fornecedores_estado_origem_id', 'estados', ['estado_origem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fornecedores_estado_origem_id', type_='foreignkey')
        batch_op.drop_column('estado_origem_id')

    # ### end Alembic commands ###
