"""create fornecedores table

Revision ID: ff60d1e97848
Revises: 7a998db8f8e6
Create Date: 2026-02-14 12:48:58.189009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff60d1e97848'
down_revision = '7a998db8f8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('total_clientes', sa.Integer(), nullable=False),
    sa.Column('avaliacoes_media', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
